### ISSUE TITLE
Ver historial de ordenes con las compras realizadas 8

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#11]
Yo como   cliente quiero ver mi historial de ordenes para saber lo que he comprado.
--
El cliente podrá acceder a una pantalla de órdenes, donde obtendrá información de sus pedidos.

**Comment by cristianbb98** [comment]
Separar en 2 requisitos. Uno para ver las compras realizadas y otro para ver el estado de las compras pendientes de ser entregadas.
