### ISSUE TITLE
Registrar productos 5

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#13]
Yo como administrador quiero registrar productos para que el usuario pueda verlos.
--
El administrador podrá ingresar nuevos productos al sistema, los cuales contendrán la siguiente información:

*  Nombre: hasta 20 caracteres alfabéticos
*  Tipo: se seleccionará entre una variedad de tipos definidos por el administrador
*  Especie: se seleccionará entre una variedad de especies definidas por el administrador
*  Precio Unitario: Precio tipo decimal con 2 decimales de precisión en dólares estadounidenses.
*  Estado: Si el producto se encuentra o no disponible

**Comment by cristianbb98** [comment]
Especificar la precisión y exactitud del tipo de dato para el campo precio.
