### ISSUE TITLE
Cambiar la disponibilidad de productos 5

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#20]
Yo como administrador quiero activar o desactivar la disponibilidad de un producto para que se muestre o no en el en el catálogo.
--
El administrador podrá cambiar la disponibilidad de un producto. Si el producto no se encuentra disponible, el producto, así como todos los combos que lo contengan no aparecerán en el catálogo al que pueden acceder los clientes

**Comment by cristianbb98** [comment]
Cambiar requisito: "de productos" por "un producto".
