### ISSUE TITLE
Asignar repartidores por disponibilidad 13

### ISSUE THREAD

**Issue by fabio1514** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#22]
El   Sistema debe asignar repartidores a los pedidos según su disponibilidad
--
En el momento que un pedido es efectuado, el sistema asignará la entrega del producto solo a aquellos repartidores que: 

1.  se encuentren disponibles en su estado
2.  se encuentren dentro de su horario de disponibilidad

**Comment by fabio1514** [comment]
@Ernesteins , será que le quitamos esta issue, que le veo medio fregada de implementar

**Comment by cristianbb98** [comment]
Modificar punto 1 y omitir punto 2 ya que son redundates.

**Comment by Ernesteins** [comment]
Nuevo issue de asignacion de repartidores
