### ISSUE TITLE
Envío de Correo de Ofertas o Combos 3

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#3]
Yo como Administrador quiero enviar correos a todos mis clientes para enseñar nuevas ofertas y promociones
--

**Comment by fabio1514** [comment]
El sistema permitirá enviar correos electrónicos a todos los clientes que se hayan registrado en el sistema y hayan aceptado recibir correos en el momento del registro. El correo adicional mente contendrá un link para de-suscribirse al envío de información

**Comment by cristianbb98** [comment]
Cambiar formato a: "Yo como usuario quiero enviar correos a los clientes..."
