### ISSUE TITLE
Registrar los datos de una tarjeta como método de pago para finalizar la compra 8

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#8]
Yo como cliente quiero registrar los datos de la tarjeta como método de pago para finalizar la compra
--
El cliente podrá registrar en el sistema los datos de una tarjeta de crédito, la cual podrá usar como método de pago para realizar la compra.

Los datos de la tarjeta son:

*  Número de la tarjeta
*  Propietario
*  Fecha de Vencimiento
*  CV de la tarjeta

Adicional se pedirá el código de seguridad de tres dígitos antes de realizar cada compra

**Comment by cristianbb98** [comment]
Añadir CV de tarjeta de credito para la compra.
