### ISSUE TITLE
Recibir un correo con la información de cuando se entregará la compra 8

### ISSUE THREAD

**Issue by fandres51** [2019-a-gr2-web/Proyecto-Yaselga-Enriquez-Pogo#9]
Yo como administrador quiero enviar un correo para informar a un cliente cuando se hará la entregará.
--
El cliente recibirá un correo de confirmación cada vez que realice una compra. En este se detallará la fecha y hora estimada de entrega.

**Comment by cristianbb98** [comment]
Cambiar a: "Yo como usuario quiero enviar correo a los clientes ...."
